[package]
name = "animation_wall"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
 
wasm-bindgen = "0.2.78" # Pour lier les fonctions Rust avec JavaScript

[lib]
crate-type = ["cdylib"] # Nécessaire pour WebAssembly

